### ISSUE TITLE
pyhocon.exceptions.ConfigMissingException: 'No configuration setting found for key basic_bs'

### ISSUE THREAD

**Issue by nobel861017** [chenyaofo/image-classification-codebase#2]
Hi, 
I ran 
```
CUDA_VISIBLE_DEVICES=0 python -m entry.run --conf conf/cifar100.conf -o output/cifar100/resnet20
```
and got the error
```
Traceback (most recent call last):
  File "/home/gerber531/anaconda3/envs/cifar100/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/gerber531/anaconda3/envs/cifar100/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/gerber531/Desktop/SPML/hw1/image-classification-codebase/entry/run.py", line 6, in <module>
    main(get_args())
  File "/home/gerber531/Desktop/SPML/hw1/image-classification-codebase/codebase/main.py", line 235, in main
    main_worker(local_rank, ngpus_per_node, args, args.conf)
  File "/home/gerber531/Desktop/SPML/hw1/image-classification-codebase/codebase/main.py", line 204, in main_worker
    prepare_for_training(conf, args.output_dir, local_rank)
  File "/home/gerber531/Desktop/SPML/hw1/image-classification-codebase/codebase/main.py", line 143, in prepare_for_training
    basic_bs = optimizer_config.pop("basic_bs")
  File "/home/gerber531/anaconda3/envs/cifar100/lib/python3.9/site-packages/pyhocon/config_tree.py", line 248, in pop
    value = self.get(key, UndefinedKey)
  File "/home/gerber531/anaconda3/envs/cifar100/lib/python3.9/site-packages/pyhocon/config_tree.py", line 210, in get
    return self._get(ConfigTree.parse_key(key), 0, default)
  File "/home/gerber531/anaconda3/envs/cifar100/lib/python3.9/site-packages/pyhocon/config_tree.py", line 150, in _get
    raise ConfigMissingException(
pyhocon.exceptions.ConfigMissingException: 'No configuration setting found for key basic_bs'
```
I printed out ```optimizer_config``` in [codebase/main.py line 141](https://github.com/chenyaofo/image-classification-codebase/blob/master/codebase/main.py#L141)
The output was 
```
ConfigTree([('type_', 'SGD'), ('lr', 0.1), ('momentum', 0.9), ('dampening', 0), ('weight_decay', 0.0005), ('nesterov', True)])
```
Seems that there is no 'basic_bs' in [conf/cifar10.conf](https://github.com/chenyaofo/image-classification-codebase/blob/master/conf/cifar10.conf#L41)

How should I solve this problem?
Thanks

**Comment by sabujlaskar** [comment]
Maybe you can try to add basic_bs = 256 in conf/cifar10 file. This setting is available in another conf file in that folder.

**Comment by chenyaofo** [comment]
Thanks for your feedbacks. I haved fix this.
